Require Ruby 3.1 or newer
puppetlabs/puppet-modulebuilder pull request #78
Opened 2024-05-25 15:49 UTC by bastelfreak

Ruby 3.0 and older are EoL. Also latest PathSpec dropped support for Ruby 3.0.

## Summary
Provide a detailed description of all the changes present in this pull request.

## Additional Context
Add any additional context about the problem here. 
- [ ] Root cause and the steps to reproduce. (If applicable)
- [ ] Thought process behind the implementation.

## Related Issues (if any)
Mention any related issues or pull requests.

## Checklist
- [ ] 🟢 Spec tests.
- [ ] 🟢 Acceptance tests.
- [ ] Manually verified.

2024-06-25 14:50 UTC, david22swan requested changes
Unfortunately this isn't something that I think we can move forward with at this time as we require support for Puppet 7 until it is dropped, and as a consequence Ruby 2.7.

2024-06-25 14:51 UTC, bastelfreak commented
Why do you require support for Puppet 7?

2024-06-25 14:59 UTC, david22swan commented
> Why do you require support for Puppet 7?

It is the current LTS Puppet Agent version and so we need to keep all of our tools compatible with it

2024-06-25 15:05 UTC, bastelfreak commented
but where does Puppet 7 rely on this tool? As far as I know you don't use it.

2024-06-25 15:19 UTC, david22swan commented
> but where does Puppet 7 rely on this tool? As far as I know you don't use it.

Will bring this to the rest of the team, my first instinct is that we require support for Puppet 7 in all things however you raise an interesting point.

2024-06-26 21:59 UTC, ekohl commented
@bastelfreak isn't it enough to mark it compatible with the latest pathspec? Can't bundler figure it out by itself that the version needs to be downgraded?

IMHO you shouldn't do a major version bump just because you want to drop an older Ruby version, unless it gives a real advantage (like cleaning up compatibility code). Here I don't see that.

2024-06-27 12:08 UTC, bastelfreak commented
>  isn't it enough to mark it compatible with the latest pathspec?

We had a problem just this week where Ruby 2.7 in our zabbix module isn't able to figure this out and tries to pull in a dependency that requires a new ruby version.

I try to be very conservative with dropping stuff, but I think there it makes sense. pdk doesn't use the gem at the moment, it duplicated the code. Breaking changes in puppet-modulebuilder basically only effect Vox Pupuli / people that use our tooling. And https://github.com/puppetlabs/puppet-modulebuilder/pull/79 should be considered a breaking change as well. I think dropping old rubies now makes sense. We need a major release anyway, the impact to the ecosystem is quite low, it allows us to use newer dependencies.

I think it makes sense to drop the rubies now when we've the chance and not later when https://github.com/puppetlabs/pdk/discussions/1360 is implemented. That will cause more prolems.

2024-06-28 10:22 UTC, david22swan commented
@bastelfreak Going to give a definitive answer as this won't be merged as we have decided to go ahead with moving the PDK towards using this gem rather than its built in modulebuilder.

As such I will go ahead and close this, thank you for the work however.

2024-06-28 10:22 UTC, closed without merging